spring.application.name=todo-hib

spring.datasource.url=jdbc:postgresql://localhost:5432/todo_hib_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# IMPORTANT: disable JPA ddl auto
spring.jpa.hibernate.ddl-auto=none

# Liquibase (if you are using it)
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
